# Generated by Django 4.2.13 on 2024-05-20 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_reservation_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='espace',
            field=models.CharField(choices=[('cinema', 'Cinema'), ('coffee', 'Coffee'), ('theatre', 'Theatre')], default='cinema', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='00000000', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='association',
            field=models.CharField(max_length=255),
        ),
    ]
