# Generated by Django 4.2.13 on 2024-05-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_remove_blogpost_image_blogimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='image',
            new_name='images',
        ),
    ]
