# Generated by Django 4.2.13 on 2024-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_rename_image_blogimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='espace',
            field=models.CharField(choices=[('cinema', 'Cinema'), ('theatre', 'Theatre')], default='cinema', max_length=10),
        ),
    ]
