# Generated by Django 4.2.13 on 2024-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_event_espace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='espace',
            field=models.CharField(choices=[('cinema', 'Cinema'), ('theatre', 'Theatre'), ('other', 'other')], default='other', max_length=10),
        ),
    ]
