# Generated by Django 4.2.13 on 2024-05-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_event_espace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='media/1.png', null=True, upload_to='media/'),
        ),
    ]
