# Generated by Django 4.2.13 on 2024-05-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_blogimage_images_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('places', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media/'),
        ),
    ]
