# Generated by Django 4.2.13 on 2024-05-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_reservationclient_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationclient',
            name='event_price',
        ),
    ]
