# Generated by Django 4.2.13 on 2024-05-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_reservationclient_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationclient',
            name='total_price',
            field=models.CharField(max_length=100),
        ),
    ]
