# Generated by Django 4.2.13 on 2024-05-29 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_rename_image_blogimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationclient',
            name='tel',
            field=models.CharField(default='00000000', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')]),
        ),
    ]
