# Generated by Django 4.2.13 on 2024-05-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_reservationclient_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
